add documentation
uashogeschoolutrecht/docs-hpc pull request #25
Opened 2022-12-14 09:59 UTC by RinsRutgers

End user documentation

2022-12-14 11:32 UTC, StefHi commented on _docs/Research Cloud/Aanbod verschillende workspaces/DataIKU.md
> +Na het starten van je workspace kom je voor de eerste keer op een aanmeld pagina. Doorloop deze stappen.
Doorloop de volgende stappen.

2022-12-14 11:54 UTC, StefHi requested changes
Duidelijke tekst! Enkel 2 kleine schrijffoutjes en ik zou de eerste zin iets anders formuleren. 
aanmeld pagina = aanmeldpagina 
hiervor = hiervoor

2022-12-14 11:54 UTC, StefHi commented on _docs/Research Cloud/Aanbod verschillende workspaces/DataIKU.md
> +Belangrijk: Verander je wachtwoord direct na het inloggen. Ga hiervor naar administration >  security > klik op admin
Ga hiervoor naar administration > security > klik op admin

2022-12-14 11:54 UTC, StefHi commented on _docs/Research Cloud/Aanbod verschillende workspaces/DataIKU.md
> +Na het starten van je workspace kom je voor de eerste keer op een aanmeld pagina. Doorloop deze stappen.
Na het starten van je workspace kom je eerst op een aanmeldpagina terecht. Daar doorloop je de volgende stappen:

2022-12-15 12:49 UTC, RinsRutgers commented on _docs/Research Cloud/Aanbod verschillende workspaces/DataIKU.md
> +Belangrijk: Verander je wachtwoord direct na het inloggen. Ga hiervor naar administration >  security > klik op admin
done

2022-12-15 12:49 UTC, merged